# Generated by Django 2.1.3 on 2019-01-15 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('birthdate', models.DateTimeField(default=datetime.datetime(2019, 1, 15, 14, 7, 33, 195805))),
                ('placeofbirth', models.CharField(max_length=200, null=True)),
                ('class_attend', models.CharField(max_length=200, null=True)),
                ('school', models.CharField(max_length=200, null=True)),
                ('father', models.CharField(max_length=200, null=True)),
                ('mother', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
