# Generated by Django 2.1.3 on 2019-01-16 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20190116_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_students',
            name='family_history',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='list_students',
            name='Family_status',
            field=models.CharField(choices=[('Fatherless', 'Fatherless'), ('Motherless', 'Motherless'), ('Parents', 'Parents')], default='Parents', max_length=20),
        ),
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 12, 42, 43, 998724), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='list_students',
            name='class_attend',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='list_students',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
