# Generated by Django 2.1.3 on 2019-01-19 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20190119_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 17, 10, 9, 75853), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
