# Generated by Django 2.1.3 on 2019-01-21 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20190120_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 15, 51, 56, 508078), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='list_students',
            name='image',
            field=models.FileField(blank=True, default='default.png', upload_to='media/'),
        ),
    ]
