# Generated by Django 2.1.3 on 2019-01-22 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20190121_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default.png', upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='list_students',
            name='image',
        ),
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 14, 22, 32, 999122), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
