# Generated by Django 2.1.3 on 2019-03-12 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20190124_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 14, 29, 17, 295350), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
