# Generated by Django 2.1.3 on 2019-03-12 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_auto_20190312_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_students',
            name='Proimage',
            field=models.ImageField(blank=True, default='none', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 14, 33, 11, 79526), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
