# Generated by Django 2.1.3 on 2019-03-12 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_auto_20190312_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='Proimage',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 14, 47, 45, 558379), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
