# Generated by Django 2.1.3 on 2019-03-18 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_auto_20190313_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 21, 50, 31, 813223), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
