# Generated by Django 2.1.3 on 2019-03-19 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_auto_20190318_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_students',
            name='Proimage',
        ),
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 7, 18, 58, 830365), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
