# Generated by Django 2.1.3 on 2019-03-19 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_auto_20190319_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 7, 19, 55, 648936), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
