# Generated by Django 2.1.3 on 2019-04-13 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0027_auto_20190319_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 21, 25, 18, 621416), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
