# Generated by Django 2.1.3 on 2019-04-14 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_auto_20190413_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_students',
            name='Proimage',
            field=models.ImageField(blank=True, default='default.png', null='True', upload_to='media/'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 22, 2, 27, 682514), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
