# Generated by Django 2.1.3 on 2019-04-17 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0031_auto_20190417_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 17, 7, 20, 52, 105483), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
